packages:
  - 'packages/*'
  - 'blog'
  - 'play'
  - 'docs'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  postinstall-postinstall: true
  v-code-diff: true
  vitepress-theme-ninc: true
  vue-demi: true

minimumReleaseAge: 0
